package model.services.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 03 17:33:51 BDT 2020
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void setSessionValues(String userId, String respId);
}
