package model.services;


import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;

import javax.servlet.http.HttpSession;

import model.services.common.AppModule;


import model.view.FillAmendVOImpl;
import model.view.FillBPOVOImpl;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 03 17:33:51 BDT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }


    /**
     * Container's getter for FillBPOVO1.
     * @return FillBPOVO1
     */
    public FillBPOVOImpl getFillBPOVO1() {
        return (FillBPOVOImpl)findViewObject("FillBPOVO1");
    }


    /**
     * Container's getter for ImpSaleContrHeaderVO1.
     * @return ImpSaleContrHeaderVO1
     */
    public ViewObjectImpl getImpSaleContrHeaderVO1() {
        return (ViewObjectImpl)findViewObject("ImpSaleContrHeaderVO1");
    }


    /**
     * Container's getter for FillAmendVO1.
     * @return FillAmendVO1
     */
    public ViewObjectImpl getFillAmendVO1() {
        return (ViewObjectImpl)findViewObject("FillAmendVO1");
    }

    /**
     * Container's getter for HeaderVO_VS_FillAmendVO_VL1.
     * @return HeaderVO_VS_FillAmendVO_VL1
     */
    public ViewLinkImpl getHeaderVO_VS_FillAmendVO_VL1() {
        return (ViewLinkImpl)findViewLink("HeaderVO_VS_FillAmendVO_VL1");
    }


    /**
     * Container's getter for ImpSaleContractDetailEOView1.
     * @return ImpSaleContractDetailEOView1
     */
    public ViewObjectImpl getImpSaleContractDetailEOView1() {
        return (ViewObjectImpl)findViewObject("ImpSaleContractDetailEOView1");
    }

    /**
     * Container's getter for IedocImpSaleContrDetailKfLink1.
     * @return IedocImpSaleContrDetailKfLink1
     */
    public ViewLinkImpl getIedocImpSaleContrDetailKfLink1() {
        return (ViewLinkImpl)findViewLink("IedocImpSaleContrDetailKfLink1");
    }

    /**
     * Container's getter for ImpSaleContractAmendVO1.
     * @return ImpSaleContractAmendVO1
     */
    public ViewObjectImpl getImpSaleContractAmendVO1() {
        return (ViewObjectImpl)findViewObject("ImpSaleContractAmendVO1");
    }

    /**
     * Container's getter for DetailAmendLink1.
     * @return DetailAmendLink1
     */
    public ViewLinkImpl getDetailAmendLink1() {
        return (ViewLinkImpl)findViewLink("DetailAmendLink1");
    }

    /**
     * Container's getter for ImpSaleContrLinesVO1.
     * @return ImpSaleContrLinesVO1
     */
    public ViewObjectImpl getImpSaleContrLinesVO1() {
        return (ViewObjectImpl)findViewObject("ImpSaleContrLinesVO1");
    }

    /**
     * Container's getter for headerVovialinevoVL1.
     * @return headerVovialinevoVL1
     */
    public ViewLinkImpl getheaderVovialinevoVL1() {
        return (ViewLinkImpl)findViewLink("headerVovialinevoVL1");
    }
    

    /**
     * Method for get Session Value which will be used in WHO Column
     * @param userId
     * @param respId
     */
       public void setSessionValues(String userId, String respId) {
      //     System.out.println("UserId....." + userId);
      //     System.out.println("RespId..." + respId);
           if (userId != null) {
               FacesContext fctx = FacesContext.getCurrentInstance();
               ExternalContext ectx = fctx.getExternalContext();
               HttpSession userSession = (HttpSession)ectx.getSession(false);
               userSession.setAttribute("userId", userId);
               userSession.setAttribute("respId", respId);
           }
       }

    /**
     * Container's getter for StyleWiseQtyCalVo1.
     * @return StyleWiseQtyCalVo1
     */
    public ViewObjectImpl getStyleWiseQtyCalVo1() {
        return (ViewObjectImpl)findViewObject("StyleWiseQtyCalVo1");
    }
}
