package model.entity;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 09 18:45:58 BDT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ImpSaleContractAmendEOImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        AmendSaleLineId {
            public Object get(ImpSaleContractAmendEOImpl obj) {
                return obj.getAmendSaleLineId();
            }

            public void put(ImpSaleContractAmendEOImpl obj, Object value) {
                obj.setAmendSaleLineId((Number)value);
            }
        }
        ,
        ImpSaleDetailId {
            public Object get(ImpSaleContractAmendEOImpl obj) {
                return obj.getImpSaleDetailId();
            }

            public void put(ImpSaleContractAmendEOImpl obj, Object value) {
                obj.setImpSaleDetailId((Number)value);
            }
        }
        ,
        StyleNo {
            public Object get(ImpSaleContractAmendEOImpl obj) {
                return obj.getStyleNo();
            }

            public void put(ImpSaleContractAmendEOImpl obj, Object value) {
                obj.setStyleNo((String)value);
            }
        }
        ,
        BpoNo {
            public Object get(ImpSaleContractAmendEOImpl obj) {
                return obj.getBpoNo();
            }

            public void put(ImpSaleContractAmendEOImpl obj, Object value) {
                obj.setBpoNo((String)value);
            }
        }
        ,
        ItemDescription {
            public Object get(ImpSaleContractAmendEOImpl obj) {
                return obj.getItemDescription();
            }

            public void put(ImpSaleContractAmendEOImpl obj, Object value) {
                obj.setItemDescription((String)value);
            }
        }
        ,
        Quantity {
            public Object get(ImpSaleContractAmendEOImpl obj) {
                return obj.getQuantity();
            }

            public void put(ImpSaleContractAmendEOImpl obj, Object value) {
                obj.setQuantity((Number)value);
            }
        }
        ,
        UnitPrice {
            public Object get(ImpSaleContractAmendEOImpl obj) {
                return obj.getUnitPrice();
            }

            public void put(ImpSaleContractAmendEOImpl obj, Object value) {
                obj.setUnitPrice((Number)value);
            }
        }
        ,
        TotalValue {
            public Object get(ImpSaleContractAmendEOImpl obj) {
                return obj.getTotalValue();
            }

            public void put(ImpSaleContractAmendEOImpl obj, Object value) {
                obj.setTotalValue((Number)value);
            }
        }
        ,
        ShipExFactoryDate {
            public Object get(ImpSaleContractAmendEOImpl obj) {
                return obj.getShipExFactoryDate();
            }

            public void put(ImpSaleContractAmendEOImpl obj, Object value) {
                obj.setShipExFactoryDate((Date)value);
            }
        }
        ,
        ShipCancelExBdDate {
            public Object get(ImpSaleContractAmendEOImpl obj) {
                return obj.getShipCancelExBdDate();
            }

            public void put(ImpSaleContractAmendEOImpl obj, Object value) {
                obj.setShipCancelExBdDate((Date)value);
            }
        }
        ,
        SalesTerm {
            public Object get(ImpSaleContractAmendEOImpl obj) {
                return obj.getSalesTerm();
            }

            public void put(ImpSaleContractAmendEOImpl obj, Object value) {
                obj.setSalesTerm((String)value);
            }
        }
        ,
        Status {
            public Object get(ImpSaleContractAmendEOImpl obj) {
                return obj.getStatus();
            }

            public void put(ImpSaleContractAmendEOImpl obj, Object value) {
                obj.setStatus((String)value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(ImpSaleContractAmendEOImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(ImpSaleContractAmendEOImpl obj, Object value) {
                obj.setLastUpdateLogin((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(ImpSaleContractAmendEOImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(ImpSaleContractAmendEOImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(ImpSaleContractAmendEOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(ImpSaleContractAmendEOImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(ImpSaleContractAmendEOImpl obj) {
                return obj.getCreationDate();
            }

            public void put(ImpSaleContractAmendEOImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(ImpSaleContractAmendEOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(ImpSaleContractAmendEOImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        Attribute1 {
            public Object get(ImpSaleContractAmendEOImpl obj) {
                return obj.getAttribute1();
            }

            public void put(ImpSaleContractAmendEOImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        ImpSaleContractDetailEO {
            public Object get(ImpSaleContractAmendEOImpl obj) {
                return obj.getImpSaleContractDetailEO();
            }

            public void put(ImpSaleContractAmendEOImpl obj, Object value) {
                obj.setImpSaleContractDetailEO((ImpSaleContractDetailEOImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(ImpSaleContractAmendEOImpl object);

        public abstract void put(ImpSaleContractAmendEOImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int AMENDSALELINEID = AttributesEnum.AmendSaleLineId.index();
    public static final int IMPSALEDETAILID = AttributesEnum.ImpSaleDetailId.index();
    public static final int STYLENO = AttributesEnum.StyleNo.index();
    public static final int BPONO = AttributesEnum.BpoNo.index();
    public static final int ITEMDESCRIPTION = AttributesEnum.ItemDescription.index();
    public static final int QUANTITY = AttributesEnum.Quantity.index();
    public static final int UNITPRICE = AttributesEnum.UnitPrice.index();
    public static final int TOTALVALUE = AttributesEnum.TotalValue.index();
    public static final int SHIPEXFACTORYDATE = AttributesEnum.ShipExFactoryDate.index();
    public static final int SHIPCANCELEXBDDATE = AttributesEnum.ShipCancelExBdDate.index();
    public static final int SALESTERM = AttributesEnum.SalesTerm.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int IMPSALECONTRACTDETAILEO = AttributesEnum.ImpSaleContractDetailEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ImpSaleContractAmendEOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("model.entity.ImpSaleContractAmendEO");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for AmendSaleLineId, using the alias name AmendSaleLineId.
     * @return the AmendSaleLineId
     */
    public Number getAmendSaleLineId() {
        return (Number)getAttributeInternal(AMENDSALELINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for AmendSaleLineId.
     * @param value value to set the AmendSaleLineId
     */
    public void setAmendSaleLineId(Number value) {
        setAttributeInternal(AMENDSALELINEID, value);
    }

    /**
     * Gets the attribute value for ImpSaleDetailId, using the alias name ImpSaleDetailId.
     * @return the ImpSaleDetailId
     */
    public Number getImpSaleDetailId() {
        return (Number)getAttributeInternal(IMPSALEDETAILID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ImpSaleDetailId.
     * @param value value to set the ImpSaleDetailId
     */
    public void setImpSaleDetailId(Number value) {
        setAttributeInternal(IMPSALEDETAILID, value);
    }

    /**
     * Gets the attribute value for StyleNo, using the alias name StyleNo.
     * @return the StyleNo
     */
    public String getStyleNo() {
        return (String)getAttributeInternal(STYLENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for StyleNo.
     * @param value value to set the StyleNo
     */
    public void setStyleNo(String value) {
        setAttributeInternal(STYLENO, value);
    }

    /**
     * Gets the attribute value for BpoNo, using the alias name BpoNo.
     * @return the BpoNo
     */
    public String getBpoNo() {
        return (String)getAttributeInternal(BPONO);
    }

    /**
     * Sets <code>value</code> as the attribute value for BpoNo.
     * @param value value to set the BpoNo
     */
    public void setBpoNo(String value) {
        setAttributeInternal(BPONO, value);
    }

    /**
     * Gets the attribute value for ItemDescription, using the alias name ItemDescription.
     * @return the ItemDescription
     */
    public String getItemDescription() {
        return (String)getAttributeInternal(ITEMDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemDescription.
     * @param value value to set the ItemDescription
     */
    public void setItemDescription(String value) {
        setAttributeInternal(ITEMDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for Quantity, using the alias name Quantity.
     * @return the Quantity
     */
    public Number getQuantity() {
        return (Number)getAttributeInternal(QUANTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Quantity.
     * @param value value to set the Quantity
     */
    public void setQuantity(Number value) {
        setAttributeInternal(QUANTITY, value);
    }

    /**
     * Gets the attribute value for UnitPrice, using the alias name UnitPrice.
     * @return the UnitPrice
     */
    public Number getUnitPrice() {
        return (Number)getAttributeInternal(UNITPRICE);
    }

    /**
     * Sets <code>value</code> as the attribute value for UnitPrice.
     * @param value value to set the UnitPrice
     */
    public void setUnitPrice(Number value) {
        setAttributeInternal(UNITPRICE, value);
    }

    /**
     * Gets the attribute value for TotalValue, using the alias name TotalValue.
     * @return the TotalValue
     */
    public Number getTotalValue() {
        return (Number)getAttributeInternal(TOTALVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalValue.
     * @param value value to set the TotalValue
     */
    public void setTotalValue(Number value) {
        setAttributeInternal(TOTALVALUE, value);
    }

    /**
     * Gets the attribute value for ShipExFactoryDate, using the alias name ShipExFactoryDate.
     * @return the ShipExFactoryDate
     */
    public Date getShipExFactoryDate() {
        return (Date)getAttributeInternal(SHIPEXFACTORYDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShipExFactoryDate.
     * @param value value to set the ShipExFactoryDate
     */
    public void setShipExFactoryDate(Date value) {
        setAttributeInternal(SHIPEXFACTORYDATE, value);
    }

    /**
     * Gets the attribute value for ShipCancelExBdDate, using the alias name ShipCancelExBdDate.
     * @return the ShipCancelExBdDate
     */
    public Date getShipCancelExBdDate() {
        return (Date)getAttributeInternal(SHIPCANCELEXBDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShipCancelExBdDate.
     * @param value value to set the ShipCancelExBdDate
     */
    public void setShipCancelExBdDate(Date value) {
        setAttributeInternal(SHIPCANCELEXBDDATE, value);
    }

    /**
     * Gets the attribute value for SalesTerm, using the alias name SalesTerm.
     * @return the SalesTerm
     */
    public String getSalesTerm() {
        return (String)getAttributeInternal(SALESTERM);
    }

    /**
     * Sets <code>value</code> as the attribute value for SalesTerm.
     * @param value value to set the SalesTerm
     */
    public void setSalesTerm(String value) {
        setAttributeInternal(SALESTERM, value);
    }

    /**
     * Gets the attribute value for Status, using the alias name Status.
     * @return the Status
     */
    public String getStatus() {
        return (String)getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Status.
     * @param value value to set the Status
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin.
     * @return the LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateLogin.
     * @param value value to set the LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for Attribute1, using the alias name Attribute1.
     * @return the Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute1.
     * @param value value to set the Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity ImpSaleContractDetailEOImpl.
     */
    public ImpSaleContractDetailEOImpl getImpSaleContractDetailEO() {
        return (ImpSaleContractDetailEOImpl)getAttributeInternal(IMPSALECONTRACTDETAILEO);
    }

    /**
     * Sets <code>value</code> as the associated entity ImpSaleContractDetailEOImpl.
     */
    public void setImpSaleContractDetailEO(ImpSaleContractDetailEOImpl value) {
        setAttributeInternal(IMPSALECONTRACTDETAILEO, value);
    }


    /**
     * @param amendSaleLineId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number amendSaleLineId) {
        return new Key(new Object[]{amendSaleLineId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        oracle.jbo.server.SequenceImpl s = new oracle.jbo.server.SequenceImpl("XX_COM_EXPORT_LC_L_SEQ",getDBTransaction());
        oracle.jbo.domain.Number sVal = s.getSequenceNumber();
        setAmendSaleLineId(sVal);
    }
}
