package model.entity;

import java.sql.SQLException;

import java.util.Map;

import oracle.adf.share.ADFContext;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowInconsistentException;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Sep 06 11:37:48 BDT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ImpSaleContrHeaderEOImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
      //  super.lock();
      try {
      super.lock();
      } catch (RowInconsistentException e) {
      refresh(REFRESH_WITH_DB_ONLY_IF_UNCHANGED | REFRESH_CONTAINEES) ;

      super.lock();
      }
    }

 public int getSrNoString() {
       int srno = 0;
            String stmt = "BEGIN :1 := XX_DOC_NO_PKG.XX_SALES_CONTRACT_DOC; end;";
            java.sql.CallableStatement cs = getDBTransaction().createCallableStatement(stmt, 1);
    try {
    cs.registerOutParameter(1, oracle.jdbc.OracleTypes.NUMBER);
    cs.execute();
    srno = cs.getInt(1);
    cs.close();
    } catch (Exception e) {
    e.printStackTrace();
    }
    return srno;
    }


    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        
        Map sessionScope = ADFContext.getCurrent().getSessionScope();
        String user = (String)sessionScope.get("userId");
   //                String user = "6489";
   //     String respId = (String)sessionScope.get("respId");
  //                 String respId = "5555";
        System.out.println("Document No -->"+getSrNoString());
        if(DML_UPDATE == operation){
        try {
        setLastUpdateDate((Date)Date.getCurrentDate());
        setLastUpdatedBy(new oracle.jbo.domain.Number(user));
        } catch (SQLException f) {
        System.out.println(f.getMessage());
        }
        }
        else if (DML_INSERT == operation){

        try {
            
        System.out.println("@In INSERT DODML");
        System.out.println("operation number: " + operation);
        setSaleContractDocNo(new oracle.jbo.domain.Number(getSrNoString()));
        setCreationDate((Date)Date.getCurrentDate());
        setCreatedBy(new oracle.jbo.domain.Number(user));
        setCreatedByOriginal(new oracle.jbo.domain.Number(user));
 //       setRespId(new oracle.jbo.domain.Number(respId));


        } catch (SQLException f) {
        ;
        }
    }

        /* if(operation == DML_INSERT){
        setSaleContractDocNo(new oracle.jbo.domain.Number(getSrNoString()));
        }*/
        
        super.doDML(operation, e);
    }

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        ImpSaleHeaderId {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getImpSaleHeaderId();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setImpSaleHeaderId((Number)value);
            }
        }
        ,
        ImpSaleContractNo {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getImpSaleContractNo();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setImpSaleContractNo((String)value);
            }
        }
        ,
        ExportLcNo {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getExportLcNo();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setExportLcNo((String)value);
            }
        }
        ,
        ContractDate {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getContractDate();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setContractDate((Date)value);
            }
        }
        ,
        BuyerName {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getBuyerName();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setBuyerName((Number)value);
            }
        }
        ,
        Division {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getDivision();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setDivision((String)value);
            }
        }
        ,
        Season {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getSeason();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setSeason((String)value);
            }
        }
        ,
        SalesTerms {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getSalesTerms();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setSalesTerms((String)value);
            }
        }
        ,
        Currency {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getCurrency();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setCurrency((String)value);
            }
        }
        ,
        CommisionPerc {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getCommisionPerc();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setCommisionPerc((Number)value);
            }
        }
        ,
        CommisionType {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getCommisionType();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setCommisionType((String)value);
            }
        }
        ,
        NegotiationDays {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getNegotiationDays();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setNegotiationDays((Number)value);
            }
        }
        ,
        OrderType {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getOrderType();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setOrderType((String)value);
            }
        }
        ,
        ExportLcReplace {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getExportLcReplace();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setExportLcReplace((String)value);
            }
        }
        ,
        ContractAmmendNo {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getContractAmmendNo();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setContractAmmendNo((String)value);
            }
        }
        ,
        ContractAmmendDate {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getContractAmmendDate();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setContractAmmendDate((Date)value);
            }
        }
        ,
        ContractValue {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getContractValue();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setContractValue((Number)value);
            }
        }
        ,
        ContractQuantity {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getContractQuantity();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setContractQuantity((Number)value);
            }
        }
        ,
        LastShipDate {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getLastShipDate();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setLastShipDate((Date)value);
            }
        }
        ,
        ContractExpiryDate {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getContractExpiryDate();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setContractExpiryDate((Date)value);
            }
        }
        ,
        ExportLcValue {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getExportLcValue();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setExportLcValue((Number)value);
            }
        }
        ,
        ExportLcQuantity {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getExportLcQuantity();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setExportLcQuantity((Number)value);
            }
        }
        ,
        ExportLcDate {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getExportLcDate();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setExportLcDate((Date)value);
            }
        }
        ,
        LcIssuingBank {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getLcIssuingBank();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setLcIssuingBank((String)value);
            }
        }
        ,
        VersionNo {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getVersionNo();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setVersionNo((Number)value);
            }
        }
        ,
        VersionDate {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getVersionDate();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setVersionDate((Date)value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setLastUpdateLogin((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getCreationDate();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        Attribute1 {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getAttribute1();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getAttribute2();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getAttribute3();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getAttribute4();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getAttribute5();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getAttribute6();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getAttribute7();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getAttribute8();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getAttribute9();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getAttribute10();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getAttribute11();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getAttribute12();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getAttribute13();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getAttribute14();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getAttribute15();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        Attribute16 {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getAttribute16();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setAttribute16((String)value);
            }
        }
        ,
        Attribute17 {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getAttribute17();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setAttribute17((String)value);
            }
        }
        ,
        Attribute18 {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getAttribute18();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setAttribute18((String)value);
            }
        }
        ,
        Attribute19 {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getAttribute19();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setAttribute19((String)value);
            }
        }
        ,
        Attribute20 {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getAttribute20();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setAttribute20((String)value);
            }
        }
        ,
        Attribute21 {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getAttribute21();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setAttribute21((String)value);
            }
        }
        ,
        Attribute22 {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getAttribute22();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setAttribute22((String)value);
            }
        }
        ,
        Attribute23 {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getAttribute23();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setAttribute23((String)value);
            }
        }
        ,
        Attribute24 {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getAttribute24();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setAttribute24((String)value);
            }
        }
        ,
        Attribute25 {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getAttribute25();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setAttribute25((String)value);
            }
        }
        ,
        Attribute26 {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getAttribute26();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setAttribute26((String)value);
            }
        }
        ,
        Attribute27 {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getAttribute27();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setAttribute27((String)value);
            }
        }
        ,
        Attribute28 {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getAttribute28();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setAttribute28((String)value);
            }
        }
        ,
        Attribute29 {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getAttribute29();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setAttribute29((String)value);
            }
        }
        ,
        Attribute30 {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getAttribute30();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setAttribute30((String)value);
            }
        }
        ,
        OrgId {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getOrgId();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        SaleContractDocNo {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getSaleContractDocNo();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setSaleContractDocNo((Number)value);
            }
        }
        ,
        BuyerNameNew {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getBuyerNameNew();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setBuyerNameNew((String)value);
            }
        }
        ,
        IssuingBank {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getIssuingBank();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setIssuingBank((String)value);
            }
        }
        ,
        AdvisingBank {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getAdvisingBank();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setAdvisingBank((String)value);
            }
        }
        ,
        BuyerId {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getBuyerId();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setBuyerId((String)value);
            }
        }
        ,
        BuyerId2 {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getBuyerId2();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setBuyerId2((String)value);
            }
        }
        ,
        BranchName {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getBranchName();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setBranchName((String)value);
            }
        }
        ,
        CreatedByOriginal {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getCreatedByOriginal();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setCreatedByOriginal((Number)value);
            }
        }
        ,
        CeratedByChangeDate {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getCeratedByChangeDate();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setCeratedByChangeDate((Date)value);
            }
        }
        ,
        CommissionValue {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getCommissionValue();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setCommissionValue((Number)value);
            }
        }
        ,
        GoodsValue {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getGoodsValue();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setGoodsValue((Number)value);
            }
        }
        ,
        Status {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getStatus();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setStatus((Number)value);
            }
        }
        ,
        Status1 {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getStatus1();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setStatus1((String)value);
            }
        }
        ,
        ImpSaleContrLinesEO {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getImpSaleContrLinesEO();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ImpSaleContractDetailEO {
            public Object get(ImpSaleContrHeaderEOImpl obj) {
                return obj.getImpSaleContractDetailEO();
            }

            public void put(ImpSaleContrHeaderEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(ImpSaleContrHeaderEOImpl object);

        public abstract void put(ImpSaleContrHeaderEOImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IMPSALEHEADERID = AttributesEnum.ImpSaleHeaderId.index();
    public static final int IMPSALECONTRACTNO = AttributesEnum.ImpSaleContractNo.index();
    public static final int EXPORTLCNO = AttributesEnum.ExportLcNo.index();
    public static final int CONTRACTDATE = AttributesEnum.ContractDate.index();
    public static final int BUYERNAME = AttributesEnum.BuyerName.index();
    public static final int DIVISION = AttributesEnum.Division.index();
    public static final int SEASON = AttributesEnum.Season.index();
    public static final int SALESTERMS = AttributesEnum.SalesTerms.index();
    public static final int CURRENCY = AttributesEnum.Currency.index();
    public static final int COMMISIONPERC = AttributesEnum.CommisionPerc.index();
    public static final int COMMISIONTYPE = AttributesEnum.CommisionType.index();
    public static final int NEGOTIATIONDAYS = AttributesEnum.NegotiationDays.index();
    public static final int ORDERTYPE = AttributesEnum.OrderType.index();
    public static final int EXPORTLCREPLACE = AttributesEnum.ExportLcReplace.index();
    public static final int CONTRACTAMMENDNO = AttributesEnum.ContractAmmendNo.index();
    public static final int CONTRACTAMMENDDATE = AttributesEnum.ContractAmmendDate.index();
    public static final int CONTRACTVALUE = AttributesEnum.ContractValue.index();
    public static final int CONTRACTQUANTITY = AttributesEnum.ContractQuantity.index();
    public static final int LASTSHIPDATE = AttributesEnum.LastShipDate.index();
    public static final int CONTRACTEXPIRYDATE = AttributesEnum.ContractExpiryDate.index();
    public static final int EXPORTLCVALUE = AttributesEnum.ExportLcValue.index();
    public static final int EXPORTLCQUANTITY = AttributesEnum.ExportLcQuantity.index();
    public static final int EXPORTLCDATE = AttributesEnum.ExportLcDate.index();
    public static final int LCISSUINGBANK = AttributesEnum.LcIssuingBank.index();
    public static final int VERSIONNO = AttributesEnum.VersionNo.index();
    public static final int VERSIONDATE = AttributesEnum.VersionDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int ATTRIBUTE16 = AttributesEnum.Attribute16.index();
    public static final int ATTRIBUTE17 = AttributesEnum.Attribute17.index();
    public static final int ATTRIBUTE18 = AttributesEnum.Attribute18.index();
    public static final int ATTRIBUTE19 = AttributesEnum.Attribute19.index();
    public static final int ATTRIBUTE20 = AttributesEnum.Attribute20.index();
    public static final int ATTRIBUTE21 = AttributesEnum.Attribute21.index();
    public static final int ATTRIBUTE22 = AttributesEnum.Attribute22.index();
    public static final int ATTRIBUTE23 = AttributesEnum.Attribute23.index();
    public static final int ATTRIBUTE24 = AttributesEnum.Attribute24.index();
    public static final int ATTRIBUTE25 = AttributesEnum.Attribute25.index();
    public static final int ATTRIBUTE26 = AttributesEnum.Attribute26.index();
    public static final int ATTRIBUTE27 = AttributesEnum.Attribute27.index();
    public static final int ATTRIBUTE28 = AttributesEnum.Attribute28.index();
    public static final int ATTRIBUTE29 = AttributesEnum.Attribute29.index();
    public static final int ATTRIBUTE30 = AttributesEnum.Attribute30.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int SALECONTRACTDOCNO = AttributesEnum.SaleContractDocNo.index();
    public static final int BUYERNAMENEW = AttributesEnum.BuyerNameNew.index();
    public static final int ISSUINGBANK = AttributesEnum.IssuingBank.index();
    public static final int ADVISINGBANK = AttributesEnum.AdvisingBank.index();
    public static final int BUYERID = AttributesEnum.BuyerId.index();
    public static final int BUYERID2 = AttributesEnum.BuyerId2.index();
    public static final int BRANCHNAME = AttributesEnum.BranchName.index();
    public static final int CREATEDBYORIGINAL = AttributesEnum.CreatedByOriginal.index();
    public static final int CERATEDBYCHANGEDATE = AttributesEnum.CeratedByChangeDate.index();
    public static final int COMMISSIONVALUE = AttributesEnum.CommissionValue.index();
    public static final int GOODSVALUE = AttributesEnum.GoodsValue.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int STATUS1 = AttributesEnum.Status1.index();
    public static final int IMPSALECONTRLINESEO = AttributesEnum.ImpSaleContrLinesEO.index();
    public static final int IMPSALECONTRACTDETAILEO = AttributesEnum.ImpSaleContractDetailEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ImpSaleContrHeaderEOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("model.entity.ImpSaleContrHeaderEO");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for ImpSaleHeaderId, using the alias name ImpSaleHeaderId.
     * @return the ImpSaleHeaderId
     */
    public Number getImpSaleHeaderId() {
        return (Number)getAttributeInternal(IMPSALEHEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ImpSaleHeaderId.
     * @param value value to set the ImpSaleHeaderId
     */
    public void setImpSaleHeaderId(Number value) {
        setAttributeInternal(IMPSALEHEADERID, value);
    }

    /**
     * Gets the attribute value for ImpSaleContractNo, using the alias name ImpSaleContractNo.
     * @return the ImpSaleContractNo
     */
    public String getImpSaleContractNo() {
        return (String)getAttributeInternal(IMPSALECONTRACTNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ImpSaleContractNo.
     * @param value value to set the ImpSaleContractNo
     */
    public void setImpSaleContractNo(String value) {
        setAttributeInternal(IMPSALECONTRACTNO, value);
    }

    /**
     * Gets the attribute value for ExportLcNo, using the alias name ExportLcNo.
     * @return the ExportLcNo
     */
    public String getExportLcNo() {
        return (String)getAttributeInternal(EXPORTLCNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExportLcNo.
     * @param value value to set the ExportLcNo
     */
    public void setExportLcNo(String value) {
        setAttributeInternal(EXPORTLCNO, value);
    }

    /**
     * Gets the attribute value for ContractDate, using the alias name ContractDate.
     * @return the ContractDate
     */
    public Date getContractDate() {
        return (Date)getAttributeInternal(CONTRACTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContractDate.
     * @param value value to set the ContractDate
     */
    public void setContractDate(Date value) {
        setAttributeInternal(CONTRACTDATE, value);
    }

    /**
     * Gets the attribute value for BuyerName, using the alias name BuyerName.
     * @return the BuyerName
     */
    public Number getBuyerName() {
        return (Number)getAttributeInternal(BUYERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for BuyerName.
     * @param value value to set the BuyerName
     */
    public void setBuyerName(Number value) {
        setAttributeInternal(BUYERNAME, value);
    }

    /**
     * Gets the attribute value for Division, using the alias name Division.
     * @return the Division
     */
    public String getDivision() {
        return (String)getAttributeInternal(DIVISION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Division.
     * @param value value to set the Division
     */
    public void setDivision(String value) {
        setAttributeInternal(DIVISION, value);
    }

    /**
     * Gets the attribute value for Season, using the alias name Season.
     * @return the Season
     */
    public String getSeason() {
        return (String)getAttributeInternal(SEASON);
    }

    /**
     * Sets <code>value</code> as the attribute value for Season.
     * @param value value to set the Season
     */
    public void setSeason(String value) {
        setAttributeInternal(SEASON, value);
    }

    /**
     * Gets the attribute value for SalesTerms, using the alias name SalesTerms.
     * @return the SalesTerms
     */
    public String getSalesTerms() {
        return (String)getAttributeInternal(SALESTERMS);
    }

    /**
     * Sets <code>value</code> as the attribute value for SalesTerms.
     * @param value value to set the SalesTerms
     */
    public void setSalesTerms(String value) {
        setAttributeInternal(SALESTERMS, value);
    }

    /**
     * Gets the attribute value for Currency, using the alias name Currency.
     * @return the Currency
     */
    public String getCurrency() {
        return (String)getAttributeInternal(CURRENCY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Currency.
     * @param value value to set the Currency
     */
    public void setCurrency(String value) {
        setAttributeInternal(CURRENCY, value);
    }

    /**
     * Gets the attribute value for CommisionPerc, using the alias name CommisionPerc.
     * @return the CommisionPerc
     */
    public Number getCommisionPerc() {
        return (Number)getAttributeInternal(COMMISIONPERC);
    }

    /**
     * Sets <code>value</code> as the attribute value for CommisionPerc.
     * @param value value to set the CommisionPerc
     */
    public void setCommisionPerc(Number value) {
        setAttributeInternal(COMMISIONPERC, value);
    }

    /**
     * Gets the attribute value for CommisionType, using the alias name CommisionType.
     * @return the CommisionType
     */
    public String getCommisionType() {
        return (String)getAttributeInternal(COMMISIONTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CommisionType.
     * @param value value to set the CommisionType
     */
    public void setCommisionType(String value) {
        setAttributeInternal(COMMISIONTYPE, value);
    }

    /**
     * Gets the attribute value for NegotiationDays, using the alias name NegotiationDays.
     * @return the NegotiationDays
     */
    public Number getNegotiationDays() {
        return (Number)getAttributeInternal(NEGOTIATIONDAYS);
    }

    /**
     * Sets <code>value</code> as the attribute value for NegotiationDays.
     * @param value value to set the NegotiationDays
     */
    public void setNegotiationDays(Number value) {
        setAttributeInternal(NEGOTIATIONDAYS, value);
    }

    /**
     * Gets the attribute value for OrderType, using the alias name OrderType.
     * @return the OrderType
     */
    public String getOrderType() {
        return (String)getAttributeInternal(ORDERTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrderType.
     * @param value value to set the OrderType
     */
    public void setOrderType(String value) {
        setAttributeInternal(ORDERTYPE, value);
    }

    /**
     * Gets the attribute value for ExportLcReplace, using the alias name ExportLcReplace.
     * @return the ExportLcReplace
     */
    public String getExportLcReplace() {
        return (String)getAttributeInternal(EXPORTLCREPLACE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExportLcReplace.
     * @param value value to set the ExportLcReplace
     */
    public void setExportLcReplace(String value) {
        setAttributeInternal(EXPORTLCREPLACE, value);
    }

    /**
     * Gets the attribute value for ContractAmmendNo, using the alias name ContractAmmendNo.
     * @return the ContractAmmendNo
     */
    public String getContractAmmendNo() {
        return (String)getAttributeInternal(CONTRACTAMMENDNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContractAmmendNo.
     * @param value value to set the ContractAmmendNo
     */
    public void setContractAmmendNo(String value) {
        setAttributeInternal(CONTRACTAMMENDNO, value);
    }

    /**
     * Gets the attribute value for ContractAmmendDate, using the alias name ContractAmmendDate.
     * @return the ContractAmmendDate
     */
    public Date getContractAmmendDate() {
        return (Date)getAttributeInternal(CONTRACTAMMENDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContractAmmendDate.
     * @param value value to set the ContractAmmendDate
     */
    public void setContractAmmendDate(Date value) {
        setAttributeInternal(CONTRACTAMMENDDATE, value);
    }

    /**
     * Gets the attribute value for ContractValue, using the alias name ContractValue.
     * @return the ContractValue
     */
    public Number getContractValue() {
        return (Number)getAttributeInternal(CONTRACTVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContractValue.
     * @param value value to set the ContractValue
     */
    public void setContractValue(Number value) {
        setAttributeInternal(CONTRACTVALUE, value);
    }

    /**
     * Gets the attribute value for ContractQuantity, using the alias name ContractQuantity.
     * @return the ContractQuantity
     */
    public Number getContractQuantity() {
        return (Number)getAttributeInternal(CONTRACTQUANTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContractQuantity.
     * @param value value to set the ContractQuantity
     */
    public void setContractQuantity(Number value) {
        setAttributeInternal(CONTRACTQUANTITY, value);
    }

    /**
     * Gets the attribute value for LastShipDate, using the alias name LastShipDate.
     * @return the LastShipDate
     */
    public Date getLastShipDate() {
        return (Date)getAttributeInternal(LASTSHIPDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastShipDate.
     * @param value value to set the LastShipDate
     */
    public void setLastShipDate(Date value) {
        setAttributeInternal(LASTSHIPDATE, value);
    }

    /**
     * Gets the attribute value for ContractExpiryDate, using the alias name ContractExpiryDate.
     * @return the ContractExpiryDate
     */
    public Date getContractExpiryDate() {
        return (Date)getAttributeInternal(CONTRACTEXPIRYDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContractExpiryDate.
     * @param value value to set the ContractExpiryDate
     */
    public void setContractExpiryDate(Date value) {
        setAttributeInternal(CONTRACTEXPIRYDATE, value);
    }

    /**
     * Gets the attribute value for ExportLcValue, using the alias name ExportLcValue.
     * @return the ExportLcValue
     */
    public Number getExportLcValue() {
        return (Number)getAttributeInternal(EXPORTLCVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExportLcValue.
     * @param value value to set the ExportLcValue
     */
    public void setExportLcValue(Number value) {
        setAttributeInternal(EXPORTLCVALUE, value);
    }

    /**
     * Gets the attribute value for ExportLcQuantity, using the alias name ExportLcQuantity.
     * @return the ExportLcQuantity
     */
    public Number getExportLcQuantity() {
        return (Number)getAttributeInternal(EXPORTLCQUANTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExportLcQuantity.
     * @param value value to set the ExportLcQuantity
     */
    public void setExportLcQuantity(Number value) {
        setAttributeInternal(EXPORTLCQUANTITY, value);
    }

    /**
     * Gets the attribute value for ExportLcDate, using the alias name ExportLcDate.
     * @return the ExportLcDate
     */
    public Date getExportLcDate() {
        return (Date)getAttributeInternal(EXPORTLCDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExportLcDate.
     * @param value value to set the ExportLcDate
     */
    public void setExportLcDate(Date value) {
        setAttributeInternal(EXPORTLCDATE, value);
    }

    /**
     * Gets the attribute value for LcIssuingBank, using the alias name LcIssuingBank.
     * @return the LcIssuingBank
     */
    public String getLcIssuingBank() {
        return (String)getAttributeInternal(LCISSUINGBANK);
    }

    /**
     * Sets <code>value</code> as the attribute value for LcIssuingBank.
     * @param value value to set the LcIssuingBank
     */
    public void setLcIssuingBank(String value) {
        setAttributeInternal(LCISSUINGBANK, value);
    }

    /**
     * Gets the attribute value for VersionNo, using the alias name VersionNo.
     * @return the VersionNo
     */
    public Number getVersionNo() {
        return (Number)getAttributeInternal(VERSIONNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for VersionNo.
     * @param value value to set the VersionNo
     */
    public void setVersionNo(Number value) {
        setAttributeInternal(VERSIONNO, value);
    }

    /**
     * Gets the attribute value for VersionDate, using the alias name VersionDate.
     * @return the VersionDate
     */
    public Date getVersionDate() {
        return (Date)getAttributeInternal(VERSIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for VersionDate.
     * @param value value to set the VersionDate
     */
    public void setVersionDate(Date value) {
        setAttributeInternal(VERSIONDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin.
     * @return the LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateLogin.
     * @param value value to set the LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for Attribute1, using the alias name Attribute1.
     * @return the Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute1.
     * @param value value to set the Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for Attribute2, using the alias name Attribute2.
     * @return the Attribute2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute2.
     * @param value value to set the Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for Attribute3, using the alias name Attribute3.
     * @return the Attribute3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute3.
     * @param value value to set the Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for Attribute4, using the alias name Attribute4.
     * @return the Attribute4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute4.
     * @param value value to set the Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for Attribute5, using the alias name Attribute5.
     * @return the Attribute5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute5.
     * @param value value to set the Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for Attribute6, using the alias name Attribute6.
     * @return the Attribute6
     */
    public String getAttribute6() {
        return (String)getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute6.
     * @param value value to set the Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for Attribute7, using the alias name Attribute7.
     * @return the Attribute7
     */
    public String getAttribute7() {
        return (String)getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute7.
     * @param value value to set the Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for Attribute8, using the alias name Attribute8.
     * @return the Attribute8
     */
    public String getAttribute8() {
        return (String)getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute8.
     * @param value value to set the Attribute8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for Attribute9, using the alias name Attribute9.
     * @return the Attribute9
     */
    public String getAttribute9() {
        return (String)getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute9.
     * @param value value to set the Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for Attribute10, using the alias name Attribute10.
     * @return the Attribute10
     */
    public String getAttribute10() {
        return (String)getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute10.
     * @param value value to set the Attribute10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for Attribute11, using the alias name Attribute11.
     * @return the Attribute11
     */
    public String getAttribute11() {
        return (String)getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute11.
     * @param value value to set the Attribute11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for Attribute12, using the alias name Attribute12.
     * @return the Attribute12
     */
    public String getAttribute12() {
        return (String)getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute12.
     * @param value value to set the Attribute12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for Attribute13, using the alias name Attribute13.
     * @return the Attribute13
     */
    public String getAttribute13() {
        return (String)getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute13.
     * @param value value to set the Attribute13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for Attribute14, using the alias name Attribute14.
     * @return the Attribute14
     */
    public String getAttribute14() {
        return (String)getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute14.
     * @param value value to set the Attribute14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for Attribute15, using the alias name Attribute15.
     * @return the Attribute15
     */
    public String getAttribute15() {
        return (String)getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute15.
     * @param value value to set the Attribute15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for Attribute16, using the alias name Attribute16.
     * @return the Attribute16
     */
    public String getAttribute16() {
        return (String)getAttributeInternal(ATTRIBUTE16);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute16.
     * @param value value to set the Attribute16
     */
    public void setAttribute16(String value) {
        setAttributeInternal(ATTRIBUTE16, value);
    }

    /**
     * Gets the attribute value for Attribute17, using the alias name Attribute17.
     * @return the Attribute17
     */
    public String getAttribute17() {
        return (String)getAttributeInternal(ATTRIBUTE17);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute17.
     * @param value value to set the Attribute17
     */
    public void setAttribute17(String value) {
        setAttributeInternal(ATTRIBUTE17, value);
    }

    /**
     * Gets the attribute value for Attribute18, using the alias name Attribute18.
     * @return the Attribute18
     */
    public String getAttribute18() {
        return (String)getAttributeInternal(ATTRIBUTE18);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute18.
     * @param value value to set the Attribute18
     */
    public void setAttribute18(String value) {
        setAttributeInternal(ATTRIBUTE18, value);
    }

    /**
     * Gets the attribute value for Attribute19, using the alias name Attribute19.
     * @return the Attribute19
     */
    public String getAttribute19() {
        return (String)getAttributeInternal(ATTRIBUTE19);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute19.
     * @param value value to set the Attribute19
     */
    public void setAttribute19(String value) {
        setAttributeInternal(ATTRIBUTE19, value);
    }

    /**
     * Gets the attribute value for Attribute20, using the alias name Attribute20.
     * @return the Attribute20
     */
    public String getAttribute20() {
        return (String)getAttributeInternal(ATTRIBUTE20);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute20.
     * @param value value to set the Attribute20
     */
    public void setAttribute20(String value) {
        setAttributeInternal(ATTRIBUTE20, value);
    }

    /**
     * Gets the attribute value for Attribute21, using the alias name Attribute21.
     * @return the Attribute21
     */
    public String getAttribute21() {
        return (String)getAttributeInternal(ATTRIBUTE21);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute21.
     * @param value value to set the Attribute21
     */
    public void setAttribute21(String value) {
        setAttributeInternal(ATTRIBUTE21, value);
    }

    /**
     * Gets the attribute value for Attribute22, using the alias name Attribute22.
     * @return the Attribute22
     */
    public String getAttribute22() {
        return (String)getAttributeInternal(ATTRIBUTE22);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute22.
     * @param value value to set the Attribute22
     */
    public void setAttribute22(String value) {
        setAttributeInternal(ATTRIBUTE22, value);
    }

    /**
     * Gets the attribute value for Attribute23, using the alias name Attribute23.
     * @return the Attribute23
     */
    public String getAttribute23() {
        return (String)getAttributeInternal(ATTRIBUTE23);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute23.
     * @param value value to set the Attribute23
     */
    public void setAttribute23(String value) {
        setAttributeInternal(ATTRIBUTE23, value);
    }

    /**
     * Gets the attribute value for Attribute24, using the alias name Attribute24.
     * @return the Attribute24
     */
    public String getAttribute24() {
        return (String)getAttributeInternal(ATTRIBUTE24);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute24.
     * @param value value to set the Attribute24
     */
    public void setAttribute24(String value) {
        setAttributeInternal(ATTRIBUTE24, value);
    }

    /**
     * Gets the attribute value for Attribute25, using the alias name Attribute25.
     * @return the Attribute25
     */
    public String getAttribute25() {
        return (String)getAttributeInternal(ATTRIBUTE25);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute25.
     * @param value value to set the Attribute25
     */
    public void setAttribute25(String value) {
        setAttributeInternal(ATTRIBUTE25, value);
    }

    /**
     * Gets the attribute value for Attribute26, using the alias name Attribute26.
     * @return the Attribute26
     */
    public String getAttribute26() {
        return (String)getAttributeInternal(ATTRIBUTE26);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute26.
     * @param value value to set the Attribute26
     */
    public void setAttribute26(String value) {
        setAttributeInternal(ATTRIBUTE26, value);
    }

    /**
     * Gets the attribute value for Attribute27, using the alias name Attribute27.
     * @return the Attribute27
     */
    public String getAttribute27() {
        return (String)getAttributeInternal(ATTRIBUTE27);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute27.
     * @param value value to set the Attribute27
     */
    public void setAttribute27(String value) {
        setAttributeInternal(ATTRIBUTE27, value);
    }

    /**
     * Gets the attribute value for Attribute28, using the alias name Attribute28.
     * @return the Attribute28
     */
    public String getAttribute28() {
        return (String)getAttributeInternal(ATTRIBUTE28);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute28.
     * @param value value to set the Attribute28
     */
    public void setAttribute28(String value) {
        setAttributeInternal(ATTRIBUTE28, value);
    }

    /**
     * Gets the attribute value for Attribute29, using the alias name Attribute29.
     * @return the Attribute29
     */
    public String getAttribute29() {
        return (String)getAttributeInternal(ATTRIBUTE29);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute29.
     * @param value value to set the Attribute29
     */
    public void setAttribute29(String value) {
        setAttributeInternal(ATTRIBUTE29, value);
    }

    /**
     * Gets the attribute value for Attribute30, using the alias name Attribute30.
     * @return the Attribute30
     */
    public String getAttribute30() {
        return (String)getAttributeInternal(ATTRIBUTE30);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute30.
     * @param value value to set the Attribute30
     */
    public void setAttribute30(String value) {
        setAttributeInternal(ATTRIBUTE30, value);
    }

    /**
     * Gets the attribute value for OrgId, using the alias name OrgId.
     * @return the OrgId
     */
    public Number getOrgId() {
        return (Number)getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrgId.
     * @param value value to set the OrgId
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for SaleContractDocNo, using the alias name SaleContractDocNo.
     * @return the SaleContractDocNo
     */
    public Number getSaleContractDocNo() {
        return (Number)getAttributeInternal(SALECONTRACTDOCNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for SaleContractDocNo.
     * @param value value to set the SaleContractDocNo
     */
    public void setSaleContractDocNo(Number value) {
        setAttributeInternal(SALECONTRACTDOCNO, value);
    }

    /**
     * Gets the attribute value for BuyerNameNew, using the alias name BuyerNameNew.
     * @return the BuyerNameNew
     */
    public String getBuyerNameNew() {
        return (String)getAttributeInternal(BUYERNAMENEW);
    }

    /**
     * Sets <code>value</code> as the attribute value for BuyerNameNew.
     * @param value value to set the BuyerNameNew
     */
    public void setBuyerNameNew(String value) {
        setAttributeInternal(BUYERNAMENEW, value);
    }

    /**
     * Gets the attribute value for IssuingBank, using the alias name IssuingBank.
     * @return the IssuingBank
     */
    public String getIssuingBank() {
        return (String)getAttributeInternal(ISSUINGBANK);
    }

    /**
     * Sets <code>value</code> as the attribute value for IssuingBank.
     * @param value value to set the IssuingBank
     */
    public void setIssuingBank(String value) {
        setAttributeInternal(ISSUINGBANK, value);
    }

    /**
     * Gets the attribute value for AdvisingBank, using the alias name AdvisingBank.
     * @return the AdvisingBank
     */
    public String getAdvisingBank() {
        return (String)getAttributeInternal(ADVISINGBANK);
    }

    /**
     * Sets <code>value</code> as the attribute value for AdvisingBank.
     * @param value value to set the AdvisingBank
     */
    public void setAdvisingBank(String value) {
        setAttributeInternal(ADVISINGBANK, value);
    }

    /**
     * Gets the attribute value for BuyerId, using the alias name BuyerId.
     * @return the BuyerId
     */
    public String getBuyerId() {
        return (String)getAttributeInternal(BUYERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BuyerId.
     * @param value value to set the BuyerId
     */
    public void setBuyerId(String value) {
        setAttributeInternal(BUYERID, value);
    }

    /**
     * Gets the attribute value for BuyerId2, using the alias name BuyerId2.
     * @return the BuyerId2
     */
    public String getBuyerId2() {
        return (String)getAttributeInternal(BUYERID2);
    }

    /**
     * Sets <code>value</code> as the attribute value for BuyerId2.
     * @param value value to set the BuyerId2
     */
    public void setBuyerId2(String value) {
        setAttributeInternal(BUYERID2, value);
    }

    /**
     * Gets the attribute value for BranchName, using the alias name BranchName.
     * @return the BranchName
     */
    public String getBranchName() {
        return (String)getAttributeInternal(BRANCHNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for BranchName.
     * @param value value to set the BranchName
     */
    public void setBranchName(String value) {
        setAttributeInternal(BRANCHNAME, value);
    }

    /**
     * Gets the attribute value for CreatedByOriginal, using the alias name CreatedByOriginal.
     * @return the CreatedByOriginal
     */
    public Number getCreatedByOriginal() {
        return (Number)getAttributeInternal(CREATEDBYORIGINAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedByOriginal.
     * @param value value to set the CreatedByOriginal
     */
    public void setCreatedByOriginal(Number value) {
        setAttributeInternal(CREATEDBYORIGINAL, value);
    }

    /**
     * Gets the attribute value for CeratedByChangeDate, using the alias name CeratedByChangeDate.
     * @return the CeratedByChangeDate
     */
    public Date getCeratedByChangeDate() {
        return (Date)getAttributeInternal(CERATEDBYCHANGEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CeratedByChangeDate.
     * @param value value to set the CeratedByChangeDate
     */
    public void setCeratedByChangeDate(Date value) {
        setAttributeInternal(CERATEDBYCHANGEDATE, value);
    }

    /**
     * Gets the attribute value for CommissionValue, using the alias name CommissionValue.
     * @return the CommissionValue
     */
    public Number getCommissionValue() {
        return (Number)getAttributeInternal(COMMISSIONVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CommissionValue.
     * @param value value to set the CommissionValue
     */
    public void setCommissionValue(Number value) {
        setAttributeInternal(COMMISSIONVALUE, value);
    }

    /**
     * Gets the attribute value for GoodsValue, using the alias name GoodsValue.
     * @return the GoodsValue
     */
    public Number getGoodsValue() {
        return (Number)getAttributeInternal(GOODSVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for GoodsValue.
     * @param value value to set the GoodsValue
     */
    public void setGoodsValue(Number value) {
        setAttributeInternal(GOODSVALUE, value);
    }

    /**
     * Gets the attribute value for Status, using the alias name Status.
     * @return the Status
     */
    public Number getStatus() {
        return (Number)getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Status.
     * @param value value to set the Status
     */
    public void setStatus(Number value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for Status1, using the alias name Status1.
     * @return the Status1
     */
    public String getStatus1() {
        return (String)getAttributeInternal(STATUS1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Status1.
     * @param value value to set the Status1
     */
    public void setStatus1(String value) {
        setAttributeInternal(STATUS1, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getImpSaleContrLinesEO() {
        return (RowIterator)getAttributeInternal(IMPSALECONTRLINESEO);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getImpSaleContractDetailEO() {
        return (RowIterator)getAttributeInternal(IMPSALECONTRACTDETAILEO);
    }


    /**
     * @param impSaleHeaderId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number impSaleHeaderId) {
        return new Key(new Object[]{impSaleHeaderId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        /* Sequence Generation Code of Lines by PwC */
        oracle.jbo.server.SequenceImpl s = new oracle.jbo.server.SequenceImpl("XX_COM_SALES_CONTRACT_H_SEQ",getDBTransaction());
        oracle.jbo.domain.Number sVal = s.getSequenceNumber();
        setImpSaleHeaderId(sVal);
        /* End Sequence Generation Code of Lines by PwC */
    }
}
