package model.view;

import java.sql.ResultSet;

import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.ViewRowSetImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 31 14:12:15 BDT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FillBPOVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public FillBPOVOImpl() {
    }

    /**
     * Returns the bind variable value for P_BUYER_ID.
     * @return bind variable value for P_BUYER_ID
     */
    public String getP_BUYER_ID() {
        return (String)getNamedWhereClauseParam("P_BUYER_ID");
    }

    /**
     * Sets <code>value</code> for bind variable P_BUYER_ID.
     * @param value value to bind as P_BUYER_ID
     */
    public void setP_BUYER_ID(String value) {
        setNamedWhereClauseParam("P_BUYER_ID", value);
    }

    /**
     * Returns the bind variable value for P_SEASON.
     * @return bind variable value for P_SEASON
     */
    public String getP_SEASON() {
        return (String)getNamedWhereClauseParam("P_SEASON");
    }

    /**
     * Sets <code>value</code> for bind variable P_SEASON.
     * @param value value to bind as P_SEASON
     */
    public void setP_SEASON(String value) {
        setNamedWhereClauseParam("P_SEASON", value);
    }


    /**
     * Returns the bind variable value for P_ORG_ID.
     * @return bind variable value for P_ORG_ID
     */
    public String getP_ORG_ID() {
        return (String)getNamedWhereClauseParam("P_ORG_ID");
    }

    /**
     * Sets <code>value</code> for bind variable P_ORG_ID.
     * @param value value to bind as P_ORG_ID
     */
    public void setP_ORG_ID(String value) {
        setNamedWhereClauseParam("P_ORG_ID", value);
    }

    /**
     * executeQueryForCollection - overridden for custom java data source support.
     */
    protected void executeQueryForCollection(Object qc, Object[] params,
                                             int noUserParams) {
        super.executeQueryForCollection(qc, params, noUserParams);
    }

    /**
     * hasNextForCollection - overridden for custom java data source support.
     */
    protected boolean hasNextForCollection(Object qc) {
        boolean bRet = super.hasNextForCollection(qc);
        return bRet;
    }

    /**
     * createRowFromResultSet - overridden for custom java data source support.
     */
    protected ViewRowImpl createRowFromResultSet(Object qc,
                                                 ResultSet resultSet) {
        ViewRowImpl value = super.createRowFromResultSet(qc, resultSet);
        return value;
    }

    /**
     * getQueryHitCount - overridden for custom java data source support.
     */
    public long getQueryHitCount(ViewRowSetImpl viewRowSet) {
        long value = super.getQueryHitCount(viewRowSet);
        return value;
    }
}
